version: '3.8'

services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - microservices-network

  microservicio-clientes:
    build: ./microservicio-clientes
    container_name: microservicio-clientes
    environment:
      - CASSANDRA_HOST=bdclientes
      - CASSANDRA_PORT=9042
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_KEYSPACE=bdclientes
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - bdclientes
    networks:
      - microservices-network

  microservicio-productos:
    build: ./microservicio-productos
    container_name: microservicio-productos
    environment:
      - MONGO_URI=mongodb://mongo-productos:27017/microservicio-productos
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo-productos
    networks:
      - microservices-network

  microservicio-ventas:
    build: ./microservicio-ventas
    container_name: microservicio-ventas
    environment:
      - MONGO_URI=mongodb://mongo-ventas:27017/microservicio-ventas
      - PORT=5002
    ports:
      - "5002:5002"
    depends_on:
      - mongo-ventas
    networks:
      - microservices-network

  bdclientes:
    image: cassandra:latest
    container_name: bdclientes
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_HOST=bdclientes
      - CASSANDRA_PORT=9042
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - microservices-network

  mongo-productos:
    image: mongo:4.4
    container_name: mongo-productos
    volumes:
      - mongo-productos-data:/data/db
    networks:
      - microservices-network
    ports:
      - "27017:27017"

  mongo-ventas:
    image: mongo:4.4
    container_name: mongo-ventas
    volumes:
      - mongo-ventas-data:/data/db
    networks:
      - microservices-network
    ports:
      - "27018:27017"

volumes:
  cassandra-data:
  mongo-productos-data:
  mongo-ventas-data:

networks:
  microservices-network:
    driver: bridge